### ISSUE TITLE
How can I test other settings on few-shot ability of OFA?

### ISSUE THREAD

**Issue by karin0018** [LechengKong/OneForAll#11]
Hi! First of all, thanks for your amazing work! 
In Section E.2 you provide some experiment results spanning more ways and shots on ogbn-arxiv and FB15K237 datasets, such as 3/5-ways on ogbn-arxiv and 10/20-ways on FB15K237. I want to test other ways on these datasets, like 10/20/30/40-ways, how should I do it?

Can I just modify the `config/data_config.yaml` and `config/task_config.yaml` like this :

`config/data_config.yaml`
```
FB15K237_fs_403:
  <<: *FB15K237_fs
  args:
    walk_length: null
    single_prompt_edge: True
    n_way: 40
    k_shot: 3
    base_construct: ConstructKG
    no_class_node: True
    remove_edge: True
  num_classes: 40
```
`config/task_config.yaml`
```
FB15K237_fs: &FB15K237_fs
  <<: *LR-link
  dataset: FB15K237_fs
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: FB15K237_fs

...
    - stage: valid
      split_name: valid
      dataset: FB15K237_fs_403
    - stage: valid
      split_name: test
      dataset: FB15K237_fs_403
```

if not, what should I do to test other few-shot settings?
