### ISSUE TITLE
Split of Arxiv

### ISSUE THREAD

**Issue by CurryTang** [LechengKong/OneForAll#9]
Hi! Thanks for sharing the elegant codebase. I have a problem regarding the dataset split of the `ogbn-arxiv`. I notice that the split is given by the ArxivSplitter, which is a 10-fold split, and 80% of the data are adopted as the training set, which is different from the original split. However, it seems the performance of GCN in `Table 3` is taken from OGB's leaderboard. I wonder whether the split will affect the overall performance of OFA.

**Comment by LechengKong** [comment]
Hi @CurryTang , thanks for helping us improve our paper. We will update the code and results accordingly in our revision. Meanwhile, we conducted experiment using GCN and our split, the results seem to be improved a bit.

**Comment by CurryTang** [comment]
Hi @LechengKong, I have a follow-up question regarding the evaluation of `OFA-ind-st`. It seems there are throwing some errors when I try to evaluate the performance of link prediction with the following commands `python3 run_cdm.py task_names pubmed_link d_multiple 1 d_min_ratio 1 lr 0.001 num_layers 3 num_epochs 2 dropout 0.15`. 

For Cora with the following setting, 
```
cora_link: &cora_link
  <<: *E2E-link
  eval_set_constructs:
    - stage: train
      split_name: train
      dataset: cora_link
    - stage: valid
      split_name: valid
      dataset: cora_link_eval
    - stage: test
      split_name: test
      dataset: cora_link_eval
    - stage: test
      split_name: train
      dataset: cora_link
```
It throws `ValueError: No samples to concatenate`. 

For Pubmed, it throws `IndexError: list index out of range` when conducting the validation.
